# Generated by Django 3.1.2 on 2020-11-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlkoholfreieDrinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('liter', models.FloatField()),
                ('beschreibung', models.CharField(blank=True, max_length=55, null=True)),
                ('preis', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AlkoholhaltigeDrinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('centiliter', models.FloatField()),
                ('beschreibung', models.CharField(blank=True, max_length=55, null=True)),
                ('preis', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Hauptspeise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('beschreibung', models.CharField(blank=True, max_length=55, null=True)),
                ('preis', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Nachspeise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('beschreibung', models.CharField(blank=True, max_length=55, null=True)),
                ('preis', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('beschreibung', models.CharField(blank=True, max_length=55, null=True)),
                ('preis', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vorspeise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('beschreibung', models.CharField(blank=True, max_length=55, null=True)),
                ('preis', models.FloatField()),
            ],
        ),
    ]
