# Generated by Django 3.1.2 on 2020-12-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menucard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alkoholfreiedrinks',
            name='zusatzstoffe',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='alkoholhaltigedrinks',
            name='zusatzstoffe',
            field=models.CharField(blank=True, default='', max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='hauptspeise',
            name='zusatzstoffe',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='nachspeise',
            name='zusatzstoffe',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='snacks',
            name='zusatzstoffe',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='vorspeise',
            name='zusatzstoffe',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='alkoholfreiedrinks',
            name='liter',
            field=models.DecimalField(decimal_places=2, default='', max_digits=8, max_length=8),
        ),
        migrations.AlterField(
            model_name='alkoholfreiedrinks',
            name='preis',
            field=models.DecimalField(decimal_places=2, default='', max_digits=8, max_length=8),
        ),
        migrations.AlterField(
            model_name='alkoholhaltigedrinks',
            name='centiliter',
            field=models.DecimalField(decimal_places=2, default='', max_digits=8, max_length=8),
        ),
        migrations.AlterField(
            model_name='alkoholhaltigedrinks',
            name='preis',
            field=models.DecimalField(decimal_places=2, default='', max_digits=8, max_length=8),
        ),
        migrations.AlterField(
            model_name='hauptspeise',
            name='preis',
            field=models.DecimalField(decimal_places=2, default='', max_digits=8, max_length=8),
        ),
        migrations.AlterField(
            model_name='nachspeise',
            name='preis',
            field=models.DecimalField(decimal_places=2, default='', max_digits=8, max_length=8),
        ),
        migrations.AlterField(
            model_name='snacks',
            name='preis',
            field=models.DecimalField(decimal_places=2, default='', max_digits=8, max_length=8),
        ),
        migrations.AlterField(
            model_name='vorspeise',
            name='preis',
            field=models.DecimalField(decimal_places=2, default='', max_digits=8, max_length=8),
        ),
    ]
