# Generated by Django 3.1.2 on 2020-12-20 17:17

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('menucard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Besucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=45)),
                ('nachname', models.CharField(max_length=45)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefon', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('strasse', models.CharField(max_length=45)),
                ('hausnummer', models.CharField(max_length=5)),
                ('plz', models.CharField(max_length=45)),
                ('stadt', models.CharField(max_length=45)),
                ('besucht_am', models.DateTimeField(auto_now_add=True, null=True)),
                ('kundeId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.kunde')),
            ],
        ),
    ]
