# Generated by Django 3.1.2 on 2020-11-21 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menucard', '0003_template'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
    ]
