# Generated by Django 3.1.2 on 2020-12-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auftrag',
            name='preis',
            field=models.DecimalField(decimal_places=2, default=600.0, max_digits=8, max_length=8),
        ),
    ]
