# Generated by Django 3.1.2 on 2021-01-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20201230_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auftrag',
            name='preis',
            field=models.DecimalField(decimal_places=2, default='', max_digits=8, max_length=8),
        ),
    ]
