# Generated by Django 3.1.2 on 2020-11-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20201107_1411'),
        ('crm', '0002_auto_20201107_1349'),
    ]

    operations = [
    ]
