# Generated by Django 3.1.2 on 2020-11-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_delete_menucard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sparte', models.CharField(choices=[('Vorspeisen', 'Vorspeisen'), ('Hauptspeisen', 'Hauptspeisen'), ('Nachspeisen', 'Nachspeisen'), ('Snacks', 'Snacks'), ('Alkoholfreie Getränke', 'Alkoholfreie Getränke'), ('Alkoholhaltige Getränke', 'Alkoholhaltige Getränke')], max_length=55)),
                ('preis', models.FloatField()),
            ],
        ),
    ]
