# Generated by Django 3.1.2 on 2020-11-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_produkt'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='produktname',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
