# Generated by Django 3.1.2 on 2020-11-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_produkt_produktname'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='einheit',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='produktname',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
