# Generated by Django 3.1.2 on 2020-11-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20201112_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='allergene',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produkt',
            name='inhalt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='einheit',
            field=models.CharField(choices=[('Ltr', 'Liter'), ('cl', 'Zentiliter')], max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='preis',
            field=models.FloatField(default=0.0),
        ),
    ]
