# Generated by Django 3.1.2 on 2020-11-15 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20201112_2131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produkt',
        ),
    ]
